# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings
title: Alvaro Carpio
paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: alvanxp
google_analytics: dbyll

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: AlvanXP.net

description: Stylish Jekyll Theme
author:
  name: alvan
  email: alvanxp@outlook.com
  github: alvanxp
  twitter: alvanxp
  pinterest: asd123
  linkedin: asd123
  bio: Software Development, War stories, tips!
  email_md5: c1ba47867082f833b80eb79b3ce63a14

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
